### ISSUE TITLE
Hello,could you tell me which script to use for each step, thank you!

### ISSUE THREAD

**Issue by junhull** [Lammlab/Resic#1]

**Comment by RoniHaas** [comment]
Hi, sorry I missed your message.
Basically, all you need to do is to add the paths to your files in [this function](https://github.com/Lammlab/Resic/blob/edae11a070a9ab988608ca00997c458ca109d0e9/Experiments/forontiers_jupyter/resic_run_file.py#L563) and run:
`python Experiments/forontiers_jupyter/resic_run_file.py`

**Comment by xieyunxiao** [comment]
> Hi, sorry I missed your message. Basically, all you need to do is to add the paths to your files in [this function](https://github.com/Lammlab/Resic/blob/edae11a070a9ab988608ca00997c458ca109d0e9/Experiments/forontiers_jupyter/resic_run_file.py#L563) and run: `python Experiments/forontiers_jupyter/resic_run_file.py`

Hello!
I use your tool but it has some ERROR when I run it , could you help me?

The ERROR warning is like :

- ERROR:root: -p 12 -m 2 -l 50 -n 3 --chunkmbs 200 --strata --best
- ERROR:root:edit plot failed
- Traceback (most recent call last):
- File "~/Experiments/forontiers_jupyter/editing_type_count_by_group_plot.py", line 63, in editing_type_count_by_group_plot
- plt_res, axes = stacked_bar(data,  show_values=True, value_format="{:.3f}",
- File "~/Experiments/forontiers_jupyter/bar_utils.py", line 39, in stacked_bar
- ny = len(data[0])
- IndexError: index 0 is out of bounds for axis 0 with size 0
- INFO:root: finished process running <function editing_type_count_by_group_plot at 0x2b5ba537c790>(('~/Sample_1.fastq', {'norep': {'norep'}, 'rep': {'rep'}, 'norep_hyper': {'norep_hyper_C_G', 'norep_hyper_A_T', 'norep_hyper_G_T', 'norep_hyper_A_G', 'norep_hyper_A_C', 'norep_hyper_C_T'}, 'rep_hyper': {'rep_hyper_A_C', 'rep_hyper_G_T', 'rep_hyper_C_G', 'rep_hyper_A_T', 'rep_hyper_C_T', 'rep_hyper_A_G'}}, <Experiments.forontiers_jupyter.directory_structure_definer.DirectoryStructure object at 0x2b5ba4a8d880>, {"('A', 'C')": '#d12325', "('A', 'G')": '#7C00BE', "('A', 'T')": '#55E5D8', "('A', 'N')": '#41C109', "('C', 'A')": '#DEF407', "('C', 'G')": '#9F3A7D', "('C', 'T')": '#3C2C0D', "('C', 'N')": '#089E4C', "('G', 'A')": '#F69804', "('G', 'C')": '#2482BD', "('G', 'T')": '#A0A269', "('G', 'N')": '#CC1D74', "('T', 'A')": '#1DA6CC', "('T', 'C')": '#d6adc6', "('T', 'G')": '#018439', "('T', 'N')": '#3939a7', "('N', 'A')": '#37462a', "('N', 'C')": '#11dacd', "('N', 'G')": '#ab6b5f', "('N', 'T')": '#1eb1cf', 'unchanged': '#1a48a7'}))


It seems that the problem stems from test_pipe.**snp_removal_test** , line 642, in resic_run_file.py.
I don't know where I am doing wrong. Please help me! Thanks!

**Comment by RoniHaas** [comment]
Hi @xieyunxiao, could you please check in your output directory which files have been created up to this point?
